services:
  - type: web
    name: rag-ask-your-doc
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -k uvicorn.workers.UvicornWorker main:app --timeout 120
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: 3.10.0
